name: image_loader_flutter
description: "The package enhances performance with image caching, ensuring smooth and efficient image rendering in your Flutter apps."
version: 0.0.9
homepage: https://github.com/codeislife07/image_loader_flutter

false_secrets:
  - /example/**

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image:  ^3.4.1
  photo_view: ^0.15.0

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
 